services:
  db:
    image: mysql:8
    container_name: mysql_backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - guilherme_data:/var/lib/mysql
volumes:
  guilherme_data: